# 47장 에러 처리

## 47.1 에러 처리의 필요성

에러 발생시 대처하지 않을 경우 프로그램이 강제 종료된다.
try catch 문을 사용해 에러에 대응하면 프로그램이 강제 종료되지 않는다.

## 47.2 try... catch... finally 문

```javascript
try {
  // 에러가 발생할 가능성이 있는 코드
} catch (err) {
  // try 코드 블록에서 에러 발생시 실행되는 블럭
  // try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```

## 47.3 Error 객체

에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖는다.
message 프로퍼티 -> Error 생성자 함수에 인수로 전달한 메세지
stack 프로퍼티 -> 에러를 발생시킨 콜스택 호출 정보

자바스크립트가 제공하는 Error 생성자 함수를 제공한다.

- Error
- SyntaxError
- ReferenceError
- TypeError
- RangeError
- URIError
  - encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을때 발생하는 에러 객체
- EvalError
  - eval 함수에서 발생하는 에러 객체

이 생성자 함수가 생성한 에러 객체 프로토타입은 모두 Error.prototype을 상속받는다.

## 47.4 throw 문

Error 생성자 함수로 에러 객체를 생성한다고 해서 에러가 발생하는것은 아니다.

throw 문으로 에럴 객체를 던져야 발생한다.

## 47.5 에러의 전파

에러는 호출자 방향으로 전파되고, 이는 콜 스택의 아래 방향으로 전파된다.

```javascript
const a = () => {
  throw new Error("error in a");
};

const b = () => {
  a();
};

const c = () => {
  b();
};

try {
  c();
} catch (error) {
  console.log(error);
}
```

a에서 발생한 error는 b 실행 컨텍스트> c 실행 컨텍스트-> 전역 실행 컨텍스트로 전파된다.

throw된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.
